### ISSUE TITLE
No exported LiveProgressBar

### ISSUE THREAD

**Issue by matepek** [pedromsilvapt/clui-progressbar#1]
Your example just doesn't work.

**Comment by pedromsilvapt** [comment]
I'm sorry, my mistake. The imported module should not be `clui-live`, but rather `clui-progressbar`. I'll update the README as soon as I can. In the meantime you can just replace that import and it should work fine.

```typescript
import { LiveProgressBar } from 'clui-progressbar';

// ...
```

**Comment by matepek** [comment]
Anyway, cool stuff. <3
